import os
import sqlite3
from pathlib import Path

import psycopg

ROOT = Path(__file__).resolve().parents[1]
SQLITE_PATH = os.environ.get('DATABASE_PATH') or str(ROOT / 'data' / 'career_os.db')
POSTGRES_DSN = os.environ.get('DATABASE_URL')

TABLES = [
    'users',
    'skills',
    'user_skills',
    'assessments',
    'resumes',
    'projects',
    'certificates',
    'goals',
    'email_verification_tokens',
    'password_reset_tokens',
]

SCHEMA = {
    'users': '''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            avatar TEXT,
            is_verified INTEGER DEFAULT 0,
            is_admin INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
    'skills': '''
        CREATE TABLE IF NOT EXISTS skills (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE NOT NULL
        )
    ''',
    'user_skills': '''
        CREATE TABLE IF NOT EXISTS user_skills (
            user_id INTEGER,
            skill_id INTEGER,
            level INTEGER DEFAULT 1,
            source TEXT DEFAULT 'manual',
            PRIMARY KEY (user_id, skill_id)
        )
    ''',
    'assessments': '''
        CREATE TABLE IF NOT EXISTS assessments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER,
            skill TEXT,
            score INTEGER,
            taken_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
    'resumes': '''
        CREATE TABLE IF NOT EXISTS resumes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER,
            filename TEXT,
            extracted_text TEXT,
            uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
    'projects': '''
        CREATE TABLE IF NOT EXISTS projects (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER,
            title TEXT,
            tech TEXT,
            status TEXT,
            url TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
    'certificates': '''
        CREATE TABLE IF NOT EXISTS certificates (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER,
            title TEXT,
            issuer TEXT,
            issue_date TEXT,
            url TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
    'goals': '''
        CREATE TABLE IF NOT EXISTS goals (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER,
            title TEXT,
            target_date TEXT,
            status TEXT DEFAULT 'active',
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
    'email_verification_tokens': '''
        CREATE TABLE IF NOT EXISTS email_verification_tokens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            token TEXT UNIQUE NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
    'password_reset_tokens': '''
        CREATE TABLE IF NOT EXISTS password_reset_tokens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            token TEXT UNIQUE NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    ''',
}


def ensure_sqlite_exists():
    if not os.path.exists(SQLITE_PATH):
        raise FileNotFoundError(f'SQLite database not found at {SQLITE_PATH}. Create it first with the app or restore the data file.')


def get_sqlite_rows():
    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    try:
        rows = {}
        for table in TABLES:
            rows[table] = conn.execute(f'SELECT * FROM {table}').fetchall()
        return rows
    finally:
        conn.close()


def create_postgres_schema(pg_conn):
    with pg_conn.cursor() as cur:
        for table, ddl in SCHEMA.items():
            cur.execute(ddl)
    pg_conn.commit()


def migrate_data(pg_conn, rows):
    inserted = {}
    with pg_conn.cursor() as cur:
        for table in TABLES:
            if not rows.get(table):
                inserted[table] = 0
                continue

            columns = [key for key in rows[table][0].keys()]
            placeholders = ', '.join(['%s'] * len(columns))
            cols = ', '.join(columns)
            sql = f'INSERT INTO {table} ({cols}) VALUES ({placeholders}) ON CONFLICT DO NOTHING'
            count = 0
            for row in rows[table]:
                values = [row[key] for key in columns]
                cur.execute(sql, values)
                count += 1
            inserted[table] = count
    pg_conn.commit()
    return inserted


def main():
    if not POSTGRES_DSN:
        raise SystemExit('DATABASE_URL is not set. Example: postgresql://user:pass@host:5432/career_os')

    ensure_sqlite_exists()
    sqlite_rows = get_sqlite_rows()

    with psycopg.connect(POSTGRES_DSN) as pg_conn:
        create_postgres_schema(pg_conn)
        inserted = migrate_data(pg_conn, sqlite_rows)

    print('Migration complete.')
    for table in TABLES:
        print(f'{table}: {inserted.get(table, 0)} rows copied')


if __name__ == '__main__':
    main()
